version: '3'
services:
  my-app:
    build:
      context: .
    image: mobler-nba
    container_name: mobler-nba-engine

    ports:
      - "8976:8976"
    volumes:
      - ./main:/app/main
      - ./config:/config
    restart: always
