// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          uuid.UUID          `json:"id"`
	Firstname   string             `json:"firstname"`
	Lastname    string             `json:"lastname"`
	Password    string             `json:"password"`
	Createdat   pgtype.Timestamptz `json:"createdat"`
	Updateat    pgtype.Timestamptz `json:"updateat"`
	Deletedat   pgtype.Timestamptz `json:"deletedat"`
	Activatedat pgtype.Timestamptz `json:"activatedat"`
	Email       string             `json:"email"`
	Phonenumber string             `json:"phonenumber"`
	Dateofbirth string             `json:"dateofbirth"`
	Isdeleted   pgtype.Bool        `json:"isdeleted"`
}
