// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GameStat struct {
	ID            uuid.UUID          `json:"id"`
	GameID        uuid.UUID          `json:"game_id"`
	Points        int32              `json:"points"`
	Rebounds      int32              `json:"rebounds"`
	Assists       int32              `json:"assists"`
	Steals        int32              `json:"steals"`
	Blocks        int32              `json:"blocks"`
	Fouls         int32              `json:"fouls"`
	TurnOvers     int32              `json:"turn_overs"`
	MinutesPlayed int32              `json:"minutes_played"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Player struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Team      string             `json:"team"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    uuid.UUID          `json:"team_id"`
}

type Team struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
